clang++ remote_cp_server.cpp  Util.cpp  Server.cpp -o ./server/remote_cp_server -std=c++11 -lcrypto -w
clang++ remote_cp_client.cpp  Util.cpp  Client.cpp -o ./client/remote_cp_client -std=c++11 -lcrypto -w

